#!/bin/bash

[[ -f /etc/X11/xorg.conf.d/20-intel.conf.backup ]] && sudo mv /etc/X11/xorg.conf.d/20-intel.conf.backup /etc/X11/xorg.conf.d/20-intel.conf
export HIDPI=true
startx

while [[ -z DISPLAY ]]; do sleep 1; done

[[ -f /etc/X11/xorg.conf.d/20-intel.conf ]] && sudo mv /etc/X11/xorg.conf.d/20-intel.conf /etc/X11/xorg.conf.d/20-intel.conf.backup
